server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_auth?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: secret

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

app:
  jwt:
    secret: ${JWT_SECRET}
    expire-seconds: ${JWT_Expire_Seconds}

wx:
  appid: ${WX_APPID}
  secret: ${WX_APPID}

tencent:
  cos:
    secret-id: ${COS_SECRET_ID}
    secret-key: ${COS_SECRET_KEY}
    region: "ap-chongqing"
    bucket: "user-avator-1391331368"
    url-prefix: "https://user-avator-1391331368.cos.ap-chongqing.myqcloud.com"